// ══════════════════════════════════════════════
// models/Case.js
// Stores cases submitted through the FIR Help form
// Used by: legalController.js → submitCase, getCaseById, getAllCases
// ══════════════════════════════════════════════

const mongoose = require('mongoose');

const CaseSchema = new mongoose.Schema({

  // Logged-in user who submitted (optional — guest submissions allowed)
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },

  // ── Explicit Case Management Support ──
  lawyerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  title: { type: String },
  clientName: { type: String },

  // ── Complainant Info (from the FIR form) ────
  name:  { type: String, required: false },
  phone: { type: String, required: false },
  email: { type: String },           // optional
  city:  { type: String, required: false },

  // ── Case Details ────────────────────────────
  caseType: {
    type: String,
    required: true
    // e.g. "Criminal", "Theft / Chori", "Fraud", etc.
    // matches the <select> options in the FIR form
  },

  incidentDate: { type: Date },      // optional — date of the incident

  description: {
    type: String,
    required: true                   // full description of what happened
  },

  // helpType: what the user selected they need
  // e.g. "Draft a FIR", "Find a lawyer nearby", "All of the above"
  helpType: { type: String },

  // ── Urgency ─────────────────────────────────
  // Maps to the urgency <select> in the frontend form
  urgency: {
    type: String,
    enum: ['not_urgent', 'moderate', 'urgent', 'emergency'],
    default: 'moderate'
  },

  // ── Status ──────────────────────────────────
  // Updated by admin or auto-assignment logic
  status: {
    type: String,
    enum: ['pending', 'assigned', 'resolved'],
    default: 'pending'
  },

  // ── Assignment ──────────────────────────────
  // Populated when a lawyer is assigned (manually or auto for emergency)
  assignedLawyer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Professional'              // links to Professional model
  },

  // ── AI-Generated FIR Draft ──────────────────
  // Auto-generated by Claude when helpType includes "FIR"
  firDraft: { type: String },

  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Case', CaseSchema);